#系统变量设置
com:
  alan:
    title: alan
    description: springboot
    age: 18
    code: alanCode
    #属性之间也可以相互引用，使用 ${key},比如
    add: ${com.alan.title}的年龄是${com.alan.age}

server:
  port: 8081
  servlet:
    context-path: /hh
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.alan.springboot.domain
  mapperLocations: classpath:mapping/*.xml
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #热部署文件，页面不产生缓存，及时更新
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  #引用其他配置文件
  profiles:
    include: redis
logging:
  file: springboot.log

